env:
  global:
    - PACKAGE_VERSION="1.1.6"
    - PACKAGE_ICON="https://www.enbiso.com/logo.svg"
    - PACKAGE_PROJECT="https://nlib.enbiso.com"
    - PACKAGE_REPO="https://github.com/enbiso/Enbiso.NLib"
language: csharp
mono: none
dotnet: 2.1.302
script:
  - dotnet restore
  - dotnet build -c release -o ../bin
after_success:
  - rm ./bin/*.0.0.1-local.nupkg;
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      for nupkg in ./bin/*.nupkg; do
          dotnet nuget push $nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
      done
    fi
